'use strict';

// Firefox: alias chrome -> browser (see app.js for the full explanation). No-op in Chrome.
if (typeof browser !== 'undefined') { globalThis.chrome = browser; }

const STORAGE_KEY = 'meshtabState';
const TASK_PRIORITIES = ['low', 'medium', 'high', 'critical'];
const $ = (selector) => document.querySelector(selector);
let currentTab = null;
let state = null;
let editingQuickNoteId = null;
let editingQuickTaskId = null;

function uid(prefix = 'item') { return globalThis.crypto?.randomUUID?.() || `${prefix}-${Date.now()}-${Math.random().toString(16).slice(2)}`; }
function cleanTitle(value, fallback = '') { const text=String(value||'').trim(); return (text||fallback).slice(0,100); }

function normalizeState(raw) {
  if (!raw || !Array.isArray(raw.buckets)) return { version:22, favicons:{}, settings:{openOnStart:true,pinOnStart:true,pinOnOpen:true,meshTabScope:'per-window',useMeshTabNewTab:false,homeDefaultDesktopId:'last-active',appearance:'light',showNotes:true,showTasks:true,showReminders:true}, desktops:[{id:'desktop-main',title:'Main'}], activeDesktopId:'desktop-main', notes:[], tasks:[], reminders:[], buckets:[] };
  const desktops = Array.isArray(raw.desktops) && raw.desktops.length ? raw.desktops.map((desktop) => ({ id:String(desktop.id), title:String(desktop.title||'Tab') })) : [{ id:'desktop-main', title:'Main' }];
  const ids = new Set(desktops.map((d)=>d.id)); const fallback=desktops[0].id;
  const buckets=(raw.buckets||[]).map((bucket,index)=>({ ...bucket, id:String(bucket.id||`bucket-${index}`), title:String(bucket.title||`Group ${index+1}`), parentId:bucket.parentId==null?null:String(bucket.parentId), desktopId:ids.has(String(bucket.desktopId))?String(bucket.desktopId):fallback, position:Number.isFinite(Number(bucket.position))?Number(bucket.position):index, bookmarkIds:Array.from(new Set((Array.isArray(bucket.bookmarkIds)?bucket.bookmarkIds:[]).map(String))), bookmarkLabels:bucket.bookmarkLabels&&typeof bucket.bookmarkLabels==='object'?{...bucket.bookmarkLabels}:{}, layout:bucket.layout&&typeof bucket.layout==='object'?{...bucket.layout}:{span:bucket.parentId?12:4,height:0,linkColumns:1} }));
  const notes=(Array.isArray(raw.notes)?raw.notes:[]).map((note,index)=>({ id:String(note.id||`note-${index}`), title:cleanTitle(note.title,`Note ${index+1}`), desktopId:ids.has(String(note.desktopId))?String(note.desktopId):fallback, general:Boolean(note.general), parentNoteId:note.parentNoteId==null?null:String(note.parentNoteId), position:Number.isFinite(Number(note.position))?Number(note.position):index, masked:Boolean(note.masked), html:typeof note.html==='string'?note.html:'', layout:note.layout&&typeof note.layout==='object'?{...note.layout}:{span:4,height:0,previousSpan:0} }));
  const tasks=(Array.isArray(raw.tasks)?raw.tasks:[]).map((task,index)=>{const status=task.status==='done'?'done':'open';const workState=status==='done'?'closed':(['todo','working','ongoing'].includes(task.workState)?task.workState:(task.working?'working':'todo'));return { ...task, id:String(task.id||`task-${index}`), title:cleanTitle(task.title,`Task ${index+1}`).slice(0,140), details:String(task.details||'').slice(0,1600), taskGroupId:task.taskGroupId==='general'||ids.has(String(task.taskGroupId))?String(task.taskGroupId):'general', priority:TASK_PRIORITIES.includes(task.priority)?task.priority:'medium', status, workState, working:workState==='working', workingSince:workState==='working'?String(task.workingSince||''):'', createdAt:Number.isFinite(Date.parse(task.createdAt||''))?new Date(task.createdAt).toISOString():new Date().toISOString(), updatedAt:Number.isFinite(Date.parse(task.updatedAt||''))?new Date(task.updatedAt).toISOString():new Date().toISOString(), dueDate:/^\d{4}-\d{2}-\d{2}$/.test(String(task.dueDate||''))?String(task.dueDate):'', completedAt:status==='done'&&Number.isFinite(Date.parse(task.completedAt||''))?new Date(task.completedAt).toISOString():'', closureNotes:String(task.closureNotes||''), minutesSpent:Math.max(0,Number.parseInt(task.minutesSpent,10)||0) };});
  const taskIds=new Set(tasks.map((task)=>task.id)); const reminders=(Array.isArray(raw.reminders)?raw.reminders:[]).map((reminder,index)=>{const normalized=MeshTabReminders.normalizeReminder(reminder,index);if(normalized.linkedTaskId&&!taskIds.has(normalized.linkedTaskId))normalized.linkedTaskId='';return normalized;});
  const legacyStartup=typeof raw.settings?.openPinnedOnStartup==='boolean'?raw.settings.openPinnedOnStartup:null;const settings={...(raw.settings||{}),openOnStart:typeof raw.settings?.openOnStart==='boolean'?raw.settings.openOnStart:(legacyStartup??true),pinOnStart:typeof raw.settings?.pinOnStart==='boolean'?raw.settings.pinOnStart:(legacyStartup??true),pinOnOpen:typeof raw.settings?.pinOnOpen==='boolean'?raw.settings.pinOnOpen:true,meshTabScope:raw.settings?.meshTabScope==='all-windows'?'all-windows':'per-window',useMeshTabNewTab:typeof raw.settings?.useMeshTabNewTab==='boolean'?raw.settings.useMeshTabNewTab:false,homeDefaultDesktopId:raw.settings?.homeDefaultDesktopId==='last-active'||ids.has(String(raw.settings?.homeDefaultDesktopId||''))?String(raw.settings.homeDefaultDesktopId):'last-active',appearance:['light','dark','system'].includes(raw.settings?.appearance)?raw.settings.appearance:'light',showNotes:raw.settings?.showNotes!==false,showTasks:raw.settings?.showTasks!==false,showReminders:raw.settings?.showReminders!==false};return { ...raw, version:22, favicons:raw.favicons&&typeof raw.favicons==='object'?{...raw.favicons}:{}, settings, desktops, activeDesktopId:ids.has(String(raw.activeDesktopId))?String(raw.activeDesktopId):fallback, notes, tasks, reminders, buckets };
}

async function persist() { await chrome.storage.local.set({ [STORAGE_KEY]: state }); }
function setStatus(message, type='') { const status=$('#status'); status.textContent=message; status.className=`status ${type}`.trim(); }
function chromeFaviconUrl(pageUrl) { const url=new URL(chrome.runtime.getURL('/_favicon/')); url.searchParams.set('pageUrl',pageUrl); url.searchParams.set('size','32'); return url.toString(); }
function showCurrentFavicon() { const image=$('#pageFavicon'), fallback=$('#pageFaviconFallback'), pageUrl=currentTab?.url||''; if(!pageUrl)return; image.src=currentTab?.favIconUrl||chromeFaviconUrl(pageUrl); image.addEventListener('load',()=>{image.hidden=false;fallback.hidden=true;},{once:true}); image.addEventListener('error',()=>{image.hidden=true;fallback.hidden=false;},{once:true}); }
function childrenOf(parentId, desktopId) { return state.buckets.filter((b)=>b.desktopId===desktopId&&b.parentId===parentId).sort((a,b)=>a.position-b.position); }
function addBucketOptions(select) { select.replaceChildren(); for(const desktop of state.desktops){ const group=document.createElement('optgroup'); group.label=desktop.title; const walk=(parentId,depth)=>{ for(const bucket of childrenOf(parentId,desktop.id)){ const option=document.createElement('option'); option.value=bucket.id; option.textContent=`${'  '.repeat(depth)}${depth?'- ':''}${bucket.title}`; group.append(option); walk(bucket.id,depth+1); } }; walk(null,0); if(group.children.length)select.append(group); } }

function descendantQuickNotes(noteId){const result=[];const queue=[String(noteId)];while(queue.length){const parentId=queue.shift();for(const child of (state.notes||[]).filter(n=>n.parentNoteId===parentId)){result.push(child);queue.push(child.id);}}return result;}
function noteText(note){ const holder=document.createElement('div'); holder.innerHTML=note?.html||''; return holder.textContent||''; }
function populateQuickNoteExisting(){ const select=$('#quickNoteExisting'); select.replaceChildren(); const fresh=document.createElement('option');fresh.value='';fresh.textContent='New note';select.append(fresh); const general=(state.notes||[]).filter(n=>n.general).sort((a,b)=>a.title.localeCompare(b.title)); if(general.length){const group=document.createElement('optgroup');group.label='General Notes';for(const n of general){const o=document.createElement('option');o.value=n.id;o.textContent=n.title;group.append(o);}select.append(group);} for(const desktop of state.desktops){const notes=(state.notes||[]).filter(n=>!n.general&&n.desktopId===desktop.id).sort((a,b)=>a.title.localeCompare(b.title));if(!notes.length)continue;const group=document.createElement('optgroup');group.label=`Tab — ${desktop.title}`;for(const n of notes){const o=document.createElement('option');o.value=n.id;o.textContent=n.title;group.append(o);}select.append(group);} select.value=editingQuickNoteId||''; }
function populateQuickNoteLocations(selected=null,parentId=null){const select=$('#quickNoteLocation');select.replaceChildren();if(parentId){const parent=state.notes.find(n=>n.id===parentId);if(parent){const o=document.createElement('option');o.value=`parent:${parent.id}`;o.textContent=`Inside Note — ${parent.title}`;select.append(o);}}const g=document.createElement('option');g.value='general';g.textContent='General Notes';select.append(g);for(const d of state.desktops){const o=document.createElement('option');o.value=`desktop:${d.id}`;o.textContent=`Tab — ${d.title}`;select.append(o);}const n=document.createElement('option');n.value='new-desktop';n.textContent='+ Create a new Tab';select.append(n);select.value=Array.from(select.options).some(o=>o.value===selected)?selected:`desktop:${state.activeDesktopId}`;$('#quickNoteNewTab').hidden=select.value!=='new-desktop';}
function loadQuickNote(noteId=null){editingQuickNoteId=noteId||null;const note=editingQuickNoteId?state.notes.find(n=>n.id===editingQuickNoteId):null;const parent=note?.parentNoteId?state.notes.find(n=>n.id===note.parentNoteId):null;$('#quickNoteTitle').value=note?.title||'';$('#quickNoteEditor').innerHTML=note?.html||'';$('#quickNoteMasked').checked=Boolean(note?.masked);populateQuickNoteLocations(parent?`parent:${parent.id}`:note?.general?'general':note?`desktop:${note.desktopId}`:`desktop:${state.activeDesktopId}`,parent?.id||null);populateQuickNoteExisting();$('#saveQuickNote').textContent=note?'Update Note':'Save Note';}
function sanitizeNoteHtml(source){const doc=new DOMParser().parseFromString(`<div>${source||''}</div>`,'text/html');const root=doc.body.firstElementChild;const allowed=new Set(['DIV','P','BR','IMG','A','B','STRONG','I','EM','UL','OL','LI']);for(const node of Array.from(root.querySelectorAll('*'))){if(!allowed.has(node.tagName)){node.replaceWith(...Array.from(node.childNodes));continue;}if(node.tagName==='IMG'){const src=node.getAttribute('src')||'';if(!/^data:image\/(png|jpe?g|gif|webp);base64,/i.test(src)){node.remove();continue;}for(const attr of Array.from(node.attributes))node.removeAttribute(attr.name);node.setAttribute('src',src);node.setAttribute('alt','Pasted image');continue;}if(node.tagName==='A'){let href=node.getAttribute('href')||'';try{const u=new URL(href);if(!['http:','https:'].includes(u.protocol))throw 0;href=u.href;}catch{node.replaceWith(...Array.from(node.childNodes));continue;}for(const attr of Array.from(node.attributes))node.removeAttribute(attr.name);node.setAttribute('href',href);node.setAttribute('target','_blank');node.setAttribute('rel','noopener noreferrer');continue;}for(const attr of Array.from(node.attributes))node.removeAttribute(attr.name);}return root.innerHTML.trim();}
async function quickNotePaste(event){const items=Array.from(event.clipboardData?.items||[]);const images=items.filter(i=>i.type?.startsWith('image/')).map(i=>i.getAsFile()).filter(Boolean);if(!images.length)return;event.preventDefault();for(const file of images){const dataUrl=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result||''));r.onerror=reject;r.readAsDataURL(file);});if(!/^data:image\//i.test(dataUrl))continue;const img=document.createElement('img');img.src=dataUrl;img.alt='Pasted image';const sel=window.getSelection();if(sel?.rangeCount&&$('#quickNoteEditor').contains(sel.anchorNode)){const range=sel.getRangeAt(0);range.deleteContents();range.insertNode(img);range.setStartAfter(img);range.collapse(true);sel.removeAllRanges();sel.addRange(range);}else $('#quickNoteEditor').append(img);}}

function populateQuickTaskGroups(){const select=$('#quickTaskGroup');select.replaceChildren();const g=document.createElement('option');g.value='general';g.textContent='General Tasks';select.append(g);for(const d of state.desktops){const o=document.createElement('option');o.value=d.id;o.textContent=`Tab — ${d.title}`;select.append(o);}}
function populateQuickTaskExisting(){const select=$('#quickTaskExisting');select.replaceChildren();const fresh=document.createElement('option');fresh.value='';fresh.textContent='New task';select.append(fresh);for(const task of (state.tasks||[]).filter(t=>t.status==='open').sort((a,b)=>a.title.localeCompare(b.title))){const o=document.createElement('option');o.value=task.id;o.textContent=`${task.title} — ${task.taskGroupId==='general'?'General':state.desktops.find(d=>d.id===task.taskGroupId)?.title||'Tab'}`;select.append(o);}select.value=editingQuickTaskId||'';}
function loadQuickTask(taskId=null){editingQuickTaskId=taskId||null;const task=editingQuickTaskId?state.tasks.find(t=>t.id===editingQuickTaskId):null;populateQuickTaskGroups();$('#quickTaskTitle').value=task?.title||'';$('#quickTaskDetails').value=task?.details||'';$('#quickTaskPriority').value=task?.priority||'medium';$('#quickTaskDue').value=task?.dueDate||'';$('#quickTaskGroup').value=task?.taskGroupId||state.activeDesktopId;populateQuickTaskExisting();$('#saveQuickTask').textContent=task?'Update Task':'Save Task';}


function setQuickReminderScheduleFields(){const type=$('#quickReminderSchedule').value;$('#quickReminderDateWrap').hidden=type!=='once';$('#quickReminderDays').hidden=type!=='selected-days';}
function populateQuickReminderTasks(){const select=$('#quickReminderTask');select.replaceChildren();const none=document.createElement('option');none.value='';none.textContent='No linked task';select.append(none);for(const task of [...(state.tasks||[])].sort((a,b)=>a.status===b.status?a.title.localeCompare(b.title):(a.status==='open'?-1:1))){const option=document.createElement('option');option.value=task.id;option.textContent=`${task.status==='done'?'✓ ':''}${task.title}`;select.append(option);}}
function loadQuickReminder(){const when=new Date(Date.now()+10*60000);populateQuickReminderTasks();$('#quickReminderTask').value='';$('#quickReminderTitle').value='';$('#quickReminderDetails').value='';$('#quickReminderSchedule').value='once';$('#quickReminderDate').value=MeshTabReminders.localDateKey(when);$('#quickReminderTime').value=`${String(when.getHours()).padStart(2,'0')}:${String(when.getMinutes()).padStart(2,'0')}`;document.querySelectorAll('#quickReminderDays input').forEach((input)=>{input.checked=MeshTabReminders.DEFAULT_DAYS.includes(Number(input.value));});setQuickReminderScheduleFields();}
async function saveQuickReminder(){const title=$('#quickReminderTitle').value.trim();if(!title){setStatus('Give the reminder a title.','error');return;}const scheduleType=$('#quickReminderSchedule').value;const date=$('#quickReminderDate').value;const time=$('#quickReminderTime').value;const days=Array.from(document.querySelectorAll('#quickReminderDays input:checked')).map((input)=>Number(input.value));if(scheduleType==='once'&&!date){setStatus('Choose a date.','error');return;}if(scheduleType==='selected-days'&&!days.length){setStatus('Choose at least one repeat day.','error');return;}const now=new Date().toISOString();const reminder=MeshTabReminders.normalizeReminder({id:uid('reminder'),title,details:$('#quickReminderDetails').value.trim(),linkedTaskId:$('#quickReminderTask').value||'',scheduleType,date,time,days,enabled:true,createdAt:now,updatedAt:now});if(scheduleType==='once'&&MeshTabReminders.localDateTime(reminder.date,reminder.time)<=Date.now()){setStatus('Choose a future date and time.','error');return;}state.reminders||=[];state.reminders.push(reminder);await persist();setStatus('Reminder scheduled.','success');hidePanels();}

function showPanel(which){const note=which==='note', task=which==='task', reminder=which==='reminder';$('#quickNotePanel').hidden=!note;$('#quickTaskPanel').hidden=!task;$('#quickReminderPanel').hidden=!reminder;document.body.classList.toggle('quick-open',note||task||reminder);if(note){loadQuickNote(null);setTimeout(()=>$('#quickNoteTitle').focus(),0);}if(task){loadQuickTask(null);setTimeout(()=>$('#quickTaskTitle').focus(),0);}if(reminder){loadQuickReminder();setTimeout(()=>$('#quickReminderTitle').focus(),0);}}
function hidePanels(){ $('#quickNotePanel').hidden=true;$('#quickTaskPanel').hidden=true;$('#quickReminderPanel').hidden=true;document.body.classList.remove('quick-open');editingQuickNoteId=null;editingQuickTaskId=null; }

async function saveQuickNote(){const title=$('#quickNoteTitle').value.trim();if(!title){setStatus('Give the note a title.','error');return;}let location=$('#quickNoteLocation').value, general=false, desktopId=state.activeDesktopId, parentNoteId=null;if(location==='new-desktop'){const name=($('#quickNoteNewTab').value.trim()||'Notes').slice(0,60);const desktop={id:uid('desktop'),title:name};state.desktops.push(desktop);desktopId=desktop.id;}else if(location==='general')general=true;else if(location.startsWith('desktop:'))desktopId=location.slice(8);else if(location.startsWith('parent:')){const parent=state.notes.find(n=>n.id===location.slice(7));if(parent){parentNoteId=parent.id;general=Boolean(parent.general);desktopId=parent.desktopId;}}const html=sanitizeNoteHtml($('#quickNoteEditor').innerHTML);state.notes||=[];const now=Date.now();if(editingQuickNoteId){const note=state.notes.find(n=>n.id===editingQuickNoteId);if(!note)return;note.title=title.slice(0,100);note.html=html;note.masked=$('#quickNoteMasked').checked;note.general=general;note.desktopId=desktopId;note.parentNoteId=parentNoteId;for(const child of descendantQuickNotes(note.id)){child.general=general;child.desktopId=desktopId;}}else state.notes.push({id:uid('note'),title:title.slice(0,100),html,masked:$('#quickNoteMasked').checked,general,desktopId,parentNoteId,position:now,layout:{span:parentNoteId?12:4,height:0,previousSpan:0}});await persist();setStatus(editingQuickNoteId?'Note updated.':'Note saved.','success');hidePanels();}
async function saveQuickTask(){const title=$('#quickTaskTitle').value.trim();if(!title){setStatus('Give the task a title.','error');return;}const now=new Date().toISOString();state.tasks||=[];if(editingQuickTaskId){const task=state.tasks.find(t=>t.id===editingQuickTaskId);if(!task)return;task.title=title.slice(0,140);task.details=$('#quickTaskDetails').value.trim().slice(0,1600);task.taskGroupId=$('#quickTaskGroup').value;task.priority=$('#quickTaskPriority').value;task.dueDate=$('#quickTaskDue').value;task.updatedAt=now;}else state.tasks.push({id:uid('task'),title:title.slice(0,140),details:$('#quickTaskDetails').value.trim().slice(0,1600),taskGroupId:$('#quickTaskGroup').value,priority:$('#quickTaskPriority').value,status:'open',workState:'todo',working:false,workingSince:'',createdAt:now,updatedAt:now,dueDate:$('#quickTaskDue').value,completedAt:'',closureNotes:'',minutesSpent:0});await persist();setStatus(editingQuickTaskId?'Task updated.':'Task saved.','success');hidePanels();}

function applyPopupAppearance() {
  const requested = state?.settings?.appearance || 'light';
  const dark = requested === 'dark' || (requested === 'system' && globalThis.matchMedia?.('(prefers-color-scheme: dark)')?.matches);
  document.documentElement.dataset.theme = dark ? 'dark' : 'light';
}

async function load() {
  $('#popupVersion').textContent=`v${chrome.runtime.getManifest().version}`;
  const [tab]=await chrome.tabs.query({active:true,currentWindow:true});currentTab=tab||null;
  const data=await chrome.storage.local.get(STORAGE_KEY);state=normalizeState(data[STORAGE_KEY]);applyPopupAppearance();$('#quickNoteBtn').hidden=!state.settings.showNotes;$('#quickTaskBtn').hidden=!state.settings.showTasks;$('#quickReminderBtn').hidden=!state.settings.showReminders;
  $('#pageTitle').textContent=currentTab?.title||'Current page';$('#pageUrl').textContent=currentTab?.url||'No URL available';$('#pageFaviconFallback').textContent=(currentTab?.title||currentTab?.url||'?').trim().charAt(0).toUpperCase();showCurrentFavicon();addBucketOptions($('#bucketSelect'));
  const supported=Boolean(currentTab?.url&&/^(https?|file):/i.test(currentTab.url));$('#saveBtn').disabled=!supported||state.buckets.length===0;if(!supported)setStatus('This Chrome page cannot be bookmarked.','error');if(!state.buckets.length)setStatus('Create a MeshTab group first.','error');
}

async function saveCurrentPage(){const bucketId=$('#bucketSelect').value,bucket=state.buckets.find(c=>c.id===bucketId);if(!bucket||!currentTab?.url)return;$('#saveBtn').disabled=true;setStatus('Saving...');try{const existing=await chrome.bookmarks.search({url:currentTab.url});const bookmark=existing.find(c=>c.url===currentTab.url)||await chrome.bookmarks.create({title:currentTab.title||currentTab.url,url:currentTab.url});const id=String(bookmark.id);if(!bucket.bookmarkIds.includes(id))bucket.bookmarkIds.unshift(id);if(currentTab.favIconUrl&&(/^https?:\/\//i.test(currentTab.favIconUrl)||/^data:image\//i.test(currentTab.favIconUrl)))state.favicons[currentTab.url]=currentTab.favIconUrl;await persist();setStatus(`Saved to ${bucket.title}.`,'success');}catch(error){setStatus(error?.message||'Could not save this page.','error');}finally{$('#saveBtn').disabled=false;}}
async function openMeshTab(hash=''){try{const response=await chrome.runtime.sendMessage({type:'meshtab-open',hash,windowId:currentTab?.windowId});if(!response?.ok)throw new Error(response?.error||'Could not open MeshTab');}catch(error){console.warn('MeshTab open helper failed; opening in this window.',error);await chrome.tabs.create({url:chrome.runtime.getURL(`newtab.html?mt_source=open${hash}`),active:true,pinned:state?.settings?.pinOnOpen!==false,windowId:currentTab?.windowId});}window.close();}

$('#saveBtn').addEventListener('click',saveCurrentPage);$('#openBtn').addEventListener('click',()=>openMeshTab());
$('#quickNoteBtn').addEventListener('click',()=>showPanel('note'));$('#quickTaskBtn').addEventListener('click',()=>showPanel('task'));$('#quickReminderBtn').addEventListener('click',()=>showPanel('reminder'));$('#closeQuickNote').addEventListener('click',hidePanels);$('#closeQuickTask').addEventListener('click',hidePanels);$('#closeQuickReminder').addEventListener('click',hidePanels);
$('#quickNoteExisting').addEventListener('change',(e)=>loadQuickNote(e.target.value||null));$('#quickNoteLocation').addEventListener('change',(e)=>$('#quickNoteNewTab').hidden=e.target.value!=='new-desktop');$('#quickNoteEditor').addEventListener('paste',quickNotePaste);$('#saveQuickNote').addEventListener('click',saveQuickNote);
document.querySelectorAll('.quick-note-toolbar-btn[data-note-format]').forEach((button)=>{button.addEventListener('mousedown',(e)=>e.preventDefault());button.addEventListener('click',()=>{$('#quickNoteEditor').focus();document.execCommand(button.dataset.noteFormat,false,null);});});
$('#quickTaskExisting').addEventListener('change',(e)=>loadQuickTask(e.target.value||null));$('#saveQuickTask').addEventListener('click',saveQuickTask);$('#openTaskCenterBtn').addEventListener('click',()=>openMeshTab('#tasks'));$('#quickReminderSchedule').addEventListener('change',setQuickReminderScheduleFields);$('#saveQuickReminder').addEventListener('click',saveQuickReminder);$('#openReminderCenterBtn').addEventListener('click',()=>openMeshTab('#reminders'));
load();
